#!/bin/bash

 export $authors_file=author.cfg

 git filter-branch -f --env-filter '

 get_name () {
     grep "^$1=" "$authors_file" |
     sed "s/^.*=\(.*\) <.*>$/\1/"
 }

 get_email () {
     grep "^$1=" "$authors_file" |
     sed "s/^.*=.* <\(.*\)>$/\1/"
 }

 GIT_AUTHOR_NAME=$(get_name $GIT_COMMITTER_NAME) &&
     GIT_AUTHOR_EMAIL=$(get_email $GIT_COMMITTER_NAME) &&
     GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME &&
     GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL &&
     export GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL &&
     export GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL
 ' -- --all

# fugangwang <kevinwangfg@gmail.com>
# git log --all --format='%aN <%cE>' |sort -u

#git filter-branch --force --commit-filter '
#        if [ "$GIT_COMMITTER_NAME" = "fugangwang" ];
#        then
#                GIT_COMMITTER_NAME="Fugang Wang";
#                GIT_AUTHOR_NAME="Fugang Wang";
#                GIT_COMMITTER_EMAIL="kevinwangfg@gmail.com";
#                GIT_AUTHOR_EMAIL="kevinwangfg@gmail.com";
#                git commit-tree "$@";
#        else
#                git commit-tree "$@";
#        fi' -- --all