#! /bin/sh

if [ $1=="system" ]; then
   echo "deploy system"
   UNAME_INFO=`uname -a`

   echo $UNAME_INFO
   case "$UNAME_INFO" in 
      *Ubuntu*) 
	   sh install-scripts/ubuntu.sh
	   exit 0
	   ;;
       *other*)
	   echo "not implemented yet"
	   exit 1
	   ;;
       *)  echo "else"
	   exit 1
	   ;;
   esac
fi

python install-scripts/install.py $@
