#!/usr/bin/env python
"""
Usage:
    install -h | --help
    install system
    install path

Description:

    install system
        install some important packages that are essential for 
        cloudmesh instalation. This command has to be called first.
        Once you have installed the command more options will be 
        available.

    install path
        lists the available sys.path for debugging purposes.

"""
from textwrap import dedent
from pprint import pprint 
import os
import getopt
import sys
from cloudmesh_common.util import banner
from cloudmesh_install.util import get_system


def print_help():
    
    deep_commands = ""
    try:
        from cloudmesh_install.install import install_command
        deep_commands = dedent(install_command.__doc__)
    except:
        deep_commands = ""
    documentation = __doc__.split("\n") + deep_commands.split("\n")
    print "\n".join(documentation)
    

def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "h", ["help"])
        if (opts == [] and args == []):
            banner( "ERROR: no parameter defined")
            print_help()
            sys.exit(1)
    except getopt.error, msg:
        print msg
        banner( "for help use --help")
        sys.exit(2)

    # parse for help
    for o, a in opts:
        if o in ("-h", "--help"):
            print_help()
            sys.exit(0)

    #
    if "help" in args:
            print_help()
            sys.exit(0)
        
    if "path" in args:

        banner ("sys.path", c="-")
        pprint(sys.path)
        banner("-")
        sys.exit(0)
                
    if "system" in args:

        banner("system")
        
        os_system = get_system()

        try:    
            os.system("bin/prepare-%s.sh" % os_system)
        except:
            print "OS distribution not supported; please see documatation for manual installation instructions."
            sys.exit(1)
        
        sys.exit(0)

    
    arguments = ' '.join(args)
    banner (arguments)
    try:

        from cloudmesh_install.install import install_command
        install_command(arguments)

    except Exception, e:
        print "ERROR: Your environment may not be properly configured."
        print "       Have you run the following command?"
        print
        print "         install system"
        print 
        print e

        
if __name__ == "__main__":
    main()
