# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
export PORTALNAME=CHANGEME
curl -sSL https://cloudmesh.github.io/get/ubuntu/ | username=$PORTALNAME sh
SCRIPT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = true
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "shell", privileged: false, inline: $script
end
