Vagrant.configure("2") do |config|
# config.vm.box = "ubuntu-14.04-server-amd64"
  config.vm.box = "ubuntu/trusty32"
  config.vm.provision :shell, path: "bootstrap.sh", :args => "'hrlee'"
  config.ssh.username = "vagrant"
end
