require 'vagrant-openstack-provider'
require 'yaml'

config = YAML.load_file(File.expand_path("~/.cloudmesh/cloudmesh.yaml"))
credential = config["cloudmesh"]["clouds"]["india"]["credentials"]


puts credential


Vagrant.configure('2') do |config|

  config.vm.box       = 'openstack'
  config.ssh.username = credential["OS_USERNAME"]

  config.vm.provider :openstack do |os|
    os.openstack_auth_url = credential["OS_AUTH_URL"]
    os.username           = credential["OS_USERNAME"]
    os.password           = credential["OS_PASSWORD"]
    os.tenant_name        = credential["OS_TENANT_NAME"]
    os.flavor             = "m1.small"
    os.image              = "futuresystems/ubuntu-14.04"
    os.floating_ip_pool   = "ext-net"
  end
end
